// Frameworks_Intro/Vue_Intro/vue-intro/src/components/PostsList.vue
<template>
  <div class="dog-post">
    <h2>A cool <strong>DOG</strong> image below!</h2>
    <h4><strong>Reload</strong> to see a new one :)</h4>

    <img alt="Dog" :src=posts.message class="dog-image">

  </div>
</template>

<script>
import axios from 'axios';

export default {
    name: "PostsList",

    data() {
        return {
            posts: []
        }
    },

    mounted() {
        axios.get('https://dog.ceo/api/breeds/image/random').then((data) => {
            console.log("data: ", data);
            console.log("data.data: ", data.data);
            console.log("data.data.message: ", data.data.message);
            this.posts = data.data
        });
    }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.dog-image {
    width: 350px;
    height: 300px;
    box-shadow: 0 0 2px 2px lightgray;
    border-radius: 7%;
}
</style>

// Frameworks_Intro/Angular_Intro/intro-prject/src/app/posts-list/posts-list.component.ts
import { Component, OnInit } from '@angular/core';
import { PostsListServiceService } from '../posts-list-service.service';

@Component({
  selector: 'app-posts-list',
  templateUrl: './posts-list.component.html',
  styleUrls: ['./posts-list.component.scss']
})

export class PostsListComponent implements OnInit {
  private postsListServiceService;
  posts: any;
  constructor(postListService: PostsListServiceService) {
    this.postsListServiceService = postListService;
  }

  
  ngOnInit(): void {
    this.getPosts();
  }

  //fetch the posts
  getPosts(): void {
    this.postsListServiceService.getPosts().subscribe((data) => {
      console.log("Data: ", data); 
      this.posts = data;
    });
  }

}


<style>
    .post-image {
        width: 400px;
        height: 300px;
        box-shadow: 0 0 2px 2px grey;
        margin: 10px 0 10px 0;
    }
</style>

<h4>That's a cool dog below!</h4>
<div>
    <img class="post-image" src="{{posts.message}}" alt="dog photo"/>
</div>
<button routerLink="/">Go Back</button>
